name: GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  HUGO_VERSION: "0.143.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache Hugo
        id: cache-hugo
        uses: actions/cache@v4
        with:
          path: ~/bin/hugo
          key: ${{ runner.os }}-hugo-${{ env.HUGO_VERSION }}

      - name: Install Hugo
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/bin
          URL="https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          curl -sSL $URL | tar -xz -C ~/bin
          chmod +x ~/bin/hugo

      - name: Add to Path
        run: |
          echo "$HOME/bin" >> $GITHUB_PATH
          hugo version

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --source exampleSite \
            --themesDir ../.. \
            --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./exampleSite/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
